export enum TOKENS {
    REFRESH_TOKEN_DURATION =  "7d",
    OPT_VERIFY_DURATION = "3600",
    JWT_TOKEN_DURATION = "1d",
    ENCRYPT_ALGORITHMS= 'RS256',
    HASH_ALGORITHMS = 'SHA256',
}

export enum  STEP_UP_POINT {
    UPDATE_PROFILE = 1,
    VERIFY_EMAIL = 5,
    UPDATE_ADDRESS = 5,
    CREATE_PROPOSAL = 5,
    VOTE_PROPOSAL = 1,
}